// app/page.tsx
import { getStoryblokApi } from '@storyblok/react/rsc'
import StoryblokStory from '@storyblok/react/story'

export async function fetchData() {
  const options = { version: process.env.NEXT_PUBLIC_STORYBLOK_VERSION }
  const storyblokApi = getStoryblokApi()

  return storyblokApi.get(`cdn/stories/home`, options)
}

export default async function Home() {
  const { data } = await fetchData()

  return <StoryblokStory story={data.story} />
}

// app.vue
<template>
  <NuxtPage />
</template>

<script lang="ts" setup>
import '@/assets/css/app.css'

// import { useStoryApi, useStoryBridge } from '@storyblok/nuxt/composables'

// const storyapi = useStoryApi()
// const { data } = await storyapi.get('cdn/stories/home', { version: 'draft' })
// const state = reactive({ stories: data.story })

// onMounted(() => {
//   useStoryBridge(state.story.id, (story) => (state.story = story))
// })
</script>
